services:
  - type: web
    name: wexa-graph-assignment
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USER
        value: cognodb
      - key: COGNODB_PASSWORD
        sync: false
      - key: PORT
        value: "10000"


